name: CI

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Install tuist
        run: bash <(curl -Ls https://install.tuist.io)
      - name: Generate project
        run: tuist generate
      - name: Build project (using tuist)
        run: tuist build
      - name: Build project (for realsies)
        run: xcodebuild build -workspace ExampleProject.xcworkspace -scheme ExampleProject

