name: Big Bang

on: push

jobs:
  build:
    name: build main project
    runs-on: macos-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Install tuist
        run: bash <(curl -Ls https://install.tuist.io)
      - name: Generate project
        run: tuist generate
      - name: lint project
        run: tuist lint project
      - name: Install xcpretty
        run: gem install xcpretty
      - name: Build for testing
        run: xcodebuild build-for-testing -workspace ExampleProject.xcworkspace -scheme ExampleProject-Project -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=14.4' -showBuildTimingSummary | xcpretty
      - name: Cache build
        uses: actions/cache@v2
        env:
          cache-name: cache-generated-build
        with:
          path:|
            /Users/runner/Library/Developer/Xcode/DerivedData
            /Users/runner/work/tuist-an-torn/tuist-an-torn
          key: ${{ runner.os }}-build-${{ env.cache-name }}
  run-unit-tests:
    name: second job
    needs: [build]
    runs-on: macos-latest
    steps:
      - name: Cache build
        uses: actions/cache@v2
        env:
          cache-name: cache-generated-build
        with:
          path: /Users/runner/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install xcpretty
        run: gem install xcpretty
      - name: Tests for ExampleProjectKit scheme
        run: xcodebuild test-without-building -scheme ExampleProjectKit -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=14.4' | xcpretty
  # run-something-else:
  #   name: third job
  #   needs: [build]
  #   runs-on: macos-latest
  #   steps:
  #     - name: Cache build
  #       uses: actions/cache@v2
  #       env:
  #         cache-name: cache-generated-build
  #       with:
  #         path: /Users/runner/Library/Developer/Xcode/DerivedData
  #         key: ${{ runner.os }}-build-${{ env.cache-name }}
  #     - name: Install xcpretty
  #       run: gem install xcpretty
  #     - name: Tests for ExampleProjectUI scheme
  #       run: xcodebuild test-without-building -scheme ExampleProjectUI -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=14.4' | xcpretty
  # run-final-tests:
  #   name: fourth job
  #   needs: [build]
  #   runs-on: macos-latest
  #   steps:
  #     - name: Cache build
  #       uses: actions/cache@v2
  #       env:
  #         cache-name: cache-generated-build
  #       with:
  #         path: /Users/runner/Library/Developer/Xcode/DerivedData#
  #         key: ${{ runner.os }}-build-${{ env.cache-name }}
  #     - name: Install xcpretty
  #       run: gem install xcpretty
  #     - name: Tests for ExampleProject scheme
  #       run: xcodebuild test-without-building -scheme ExampleProject -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=14.4' | xcpretty

