name: Big Bang

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Install tuist
        run: bash <(curl -Ls https://install.tuist.io)
      - name: Generate project
        run: tuist generate
      - name: lint project
        run: tuist lint project
      #- name: Build project (using tuist)
      #  run: tuist build
      #- name: run tests
      #  run: tuist test
      - name: Build project (using xcodebuild)
        run: xcodebuild \
             -workspace ExampleProject.xcworkspace \
             -scheme ExampleProject \
             -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=14.4' \
             -showBuildTimingSummary

