name: Big Bang

on: push

jobs:
  build:
    name: first job
    runs-on: macos-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Install tuist
        run: bash <(curl -Ls https://install.tuist.io)
      - name: Generate project
        run: tuist generate
      - name: lint project
        run: tuist lint project
      - name: Install xcpretty
        run: gem install xcpretty
      - name: Build for testing
        run: xcodebuild build-for-testing -workspace ExampleProject.xcworkspace -scheme ExampleProject-Project -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=14.4' -showBuildTimingSummary | xcpretty
      - name: Tests for ExampleProjectKit scheme
        run: xcodebuild test-without-building -scheme ExampleProjectKit -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=14.4' | xcpretty
      - name: Tests for ExampleProjectUI scheme
        run: xcodebuild test-without-building -scheme ExampleProjectUI -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=14.4' | xcpretty
      - name: Tests for ExampleProject scheme
        run: xcodebuild test-without-building -scheme ExampleProject -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=14.4' | xcpretty

  run-unit-tests:
    name: second job
    runs-on: ubuntu-latest
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Install tuist
        run: bash <(curl -Ls https://install.tuist.io)
      - name: Generate project
        run: tuist generate
      - name: lint project
        run: tuist lint project
      - name: Install xcpretty
  
  run-something-else:
    name: third job
    needs: [build, run-unit-tests]
    runs-on: ubuntu-latest
      - name: Checkout project
        uses: actions/checkout@v2

