name: Smaller bang

on: push

jobs:
  build:
    name: build main project
    runs-on: macos-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Install tuist
        run: bash <(curl -Ls https://install.tuist.io)
      - name: Generate project
        run: tuist generate
      - name: lint project
        run: tuist lint project
      - name: Install xcpretty
        run: gem install xcpretty
      - name: Build for testing
        run: xcodebuild build-for-testing -derivedDataPath ./derived-data -resultBundlePath ./result-bundle -workspace ExampleProject.xcworkspace -scheme ExampleProject-Project -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=14.4' -showBuildTimingSummary | xcpretty
      - name: Upload generated artifacts
        uses: actions/upload-artifact@v2
        with:
          name: generated artifacts
          path: |
            ./**.*
            ./derived-data/**.*
            ./result-bundle/**.*
  run-unit-tests:
    name: second job
    needs: [build]
    runs-on: macos-latest
    steps:
      - name: Download generated artifacts
        uses: actions/download-artifact@v2
        with:
          name: generated artifacts
      - name: list content
        run: ls -altr
      #- name: Install xcpretty
      #  run: gem install xcpretty
      #- name: Tests for ExampleProjectKit scheme
      #  run: xcodebuild test-without-building -scheme ExampleProjectKit -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=14.4' | xcpretty

